server:
  port: ${SERVER_PORT:8080}
jwt:
  secret: 123456
algorithm:
  secret-code: christyronie420blazeit
spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
      show-sql: true
  datasource:
    url: ${MARIADB_URL:jdbc:mariadb://localhost:3306/news-api}
    username: ${MARIADB_USER:root}
    password: ${MARIADB_PASSWORD:mypass}