server:
  port: ${SERVER_PORT:8081}
system:
  properties:
    java:
      version: ${JAVA_VERSION:17}
springdoc:
  swagger-ui:
    enabled: true
    path: /docs
spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
      show-sql: true
  datasource:
#    url: ${MARIADB_URL:jdbc:mariadb://localhost:3306/news-api}
#    username: ${MARIADB_USER:root}
#    password: ${MARIADB_PASSWORD:mypass}
    url: ${MARIADB_URL:jdbc:mariadb://ms-2nd-edition-groups-db00006104.mdb0002418.db.skysql.net:5003/group2?useSSL=true&trustServerCertificate=true}
    username: ${MARIADB_USERNAME:group2}
    password: ${MARIADB_PASSWORD:Group2Password!}